# general settings
name: Train_EC_MSEC_win8_B32G4_30k_mlr.yml
model_type: MultiExposureCorrectionModel
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: MultiExpoCorr
    type: MultiExpoPairedImageDataset
    dataroot_gt: datasets/MultiExposure_dataset/training/GT_IMAGES_sub
    dataroot_lq: datasets/MultiExposure_dataset/training/INPUT_IMAGES_sub
    meta_info_file: ec/data/meta_info/meta_info_ec_sub_lq_MSEC.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: MultiExpoCorr
    type: MultiExpoPairedImageDataset
    dataroot_gt: datasets/MultiExposure_dataset/validation/GT_IMAGES
    dataroot_lq: datasets/MultiExposure_dataset/validation/INPUT_IMAGES
    io_backend:
      type: disk

# network structures
network_g:
  type: MEC_CIT
  window_size: 8

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000]
    gamma: 0.5

  total_iter: 30000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  color_opt:
    type: L_color
    loss_weight: 0.5
  spacial_opt:
    type: L_spa
    loss_weight: 0.5

# validation settings
val:
  val_freq: !!float 2500
  save_img: false

  metrics:
    psnr:
      type: calculate_ec_psnr
    ssim:
      type: calculate_ec_ssim

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2500
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
